test_pro_temp/test_app_temp/urls.py
from django.urls import path
from test_app_temp import views

app_name = 'tapp'

urlpatterns = [
    path('Login/',views.user_login, name='user_login'),
    path('Register/', views.reg_forms, name='reg'),
    path('users/', views.index_users, name='users'),
    path('formpage/', views.index_forms, name='formpage'),

]

test_pro_temp/test_pro_temp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from test_app_temp import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('tapp/', include('test_app_temp.urls')),
    path('admin/', admin.site.urls),
    path('Logout/',views.user_logout, name='logout'),
    path('special/',views.special, name='spl'),
]

test_pro_temp/test_app_temp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class PUser(models.Model):
    name = models.CharField(max_length=264)
    email = models.EmailField(unique=True)
    text = models.CharField(max_length=264)

    def __str__(self):
        return self.name

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio = models.URLField(blank=True)
    dp = models.ImageField(upload_to='prof_pics', blank=True)

    def __str__(self):
        return self.user.username

test_pro_temp/test_app_temp/forms.py
from django import forms
from test_app_temp.models import PUser,UserInfo
from django.contrib.auth.models import User

class Aform(forms.ModelForm):
    class Meta:
        model = PUser
        fields = "__all__"

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ["username","password","email"]

class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ["portfolio","dp"]

test_pro_temp/test_app_temp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from test_app_temp.models import PUser
from . import forms
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'index_main.html')

def index_users(request):
    User_Base = PUser.objects.order_by('name')
    my_dic = {'userbase':User_Base}
    return render(request,'test_app_temp/index.html', context = my_dic )

def index_forms(request):
    tform = forms.Aform()
    if request.method == 'POST':
        tform = forms.Aform(request.POST)

        if tform.is_valid():
            print("NAME: "+tform.cleaned_data['name'])
            print("EMAIL: "+tform.cleaned_data['email'])
            print("TEXT: "+tform.cleaned_data['text'])
            tform.save()
            return index(request)

    return render(request,'test_app_temp/forms.html',{'form':tform})

def reg_forms(request):
    registered = False

    if request.method == 'POST':
        user_form = forms.UserForm(request.POST)
        userinfo_form = forms.UserInfoForm(request.POST)

        if user_form.is_valid() and userinfo_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            UI = userinfo_form.save(commit=False)
            UI.user = user

            if 'dp' in request.FILES:
                UI.dp = request.FILES['dp']

            UI.save()

            registered = True
            return HttpResponseRedirect(reverse('index'))


        else:
            print(user_form.errors,userinfo_form.errors)
    else:
        user_form = forms.UserForm()
        userinfo_form = forms.UserInfoForm()
    return render(request,'test_app_temp/register.html',{'user_form':user_form,'userinfo_form':userinfo_form,'registered':registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("You are not a active user")
        else:
            print("Thiefff")
            return HttpResponse("Invalid details")
    else:
        return render(request,'test_app_temp/ulogin.html',{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("This is a special one")

test_pro_temp/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class='navbar-brand' href="{% url 'index' %}">Home</a></li>
          <li><a class='navbar-link' href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class='navbar-link' href="{% url 'tapp:users' %}">Users</a></li>
          <li><a class='navbar-link' href="{% url 'tapp:formpage' %}">Sign Up</a></li>
          <li><a class='navbar-link' href="{% url 'tapp:reg' %}">Register</a></li>

          {% if user.is_authenticated %}
          <li><a class='navbar-link' href="{% url 'logout' %}">Logout</a></li>
          <li><a class='navbar-link' href="{% url 'spl' %}">Special</a></li>
          {% else %}
          <li><a class='navbar-link' href="{% url 'tapp:user_login' %}">Login</a></li>
          {% endif %}
        
        </ul>
      </div>
    </nav>
    <div class="container">
    <div class="jumbotron">
      {% block body_block %}
      {% endblock %}
    </div>
    </div>
  </body>
</html>

test_pro_temp/templates/index_main.html
<!DOCTYPE html>
{% extends "base.html" %}
  {% block body_block %}
    <h1> Welcome!!!!</h1>
    <h4> Please go to /users to view the users list or <a href="{% url 'tapp:users' %}"> click here </a> </h4>
    <h4> Please go to /admin to enter admin page or <a href="{% url 'admin:index' %}"> click here </a> </h4>
    <h4> Please go to /formpage to view the form for notify or <a href="{% url 'tapp:formpage' %}"> click here </a> </h4>
  {% endblock %}

test_pro_temp/templates/test_app_temp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <style>
      body {
      background-image: url("{% static 'images/lou1.jpg'%}");
      background: url('{% static 'images/lou1.jpg'%}');
      }
      .jumbotron {
        background: rgba(0, 0, 0, 0.5);
        color: #ACABAB;
      }
      .navbar-default{
        background: rgba(0, 0, 0, 0.7);
        border: none;
      }

    </style>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a style="color: white" class='navbar-brand' href="{% url 'index' %}">Home</a></li>
          <li><a style="color: white" class='navbar-link' href="{% url 'admin:index' %}">Admin</a></li>
          <li><a style="color: white" class='navbar-link' href="{% url 'tapp:users' %}">Users</a></li>
          <li><a style="color: white" class='navbar-link' href="{% url 'tapp:formpage' %}">Sign Up</a></li>
          <li><a style="color: white" class='navbar-link' href="{% url 'tapp:reg' %}">Register</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">

      {% block body_block %}
      {% endblock %}

    </div>
  </body>
</html>

test_pro_temp/templates/test_app_temp/forms.html
<!DOCTYPE html>
{% extends "test_app_temp/base.html" %}
  {% block body_block %}
     <div class="jumbotron">
      <h1> Please fill out the form below !!!</h1>
      <form  method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">

      </form>
      <h2> Please <a href="{% url "index" %}">  click here</a> to get back to Index</h2>
     </div>
  {% endblock %}

test_pro_temp/templates/test_app_temp/index.html
<!DOCTYPE html>
{% extends "base.html" %}
  {% block body_block %}
    <h2> Here are your Users list </h2>
    <div class='DjangoUser'>
      {% if userbase %}
      <ol>
       {% for ls in userbase %}
          <li> User Info</li>
            <ul>
              <li> Name : {{ls.name}} </li>
              <li> Text : {{ls.text}} </li>
              <li> email : {{ls.email}} </li>
            </ul>
       {% endfor %}
       </ol>
      {% else %}
        <p> NO RECORDS FOUND</p>
      {% endif %}
    </div>
    <h3> Please <a href="{% url 'index' %}">  click here</a> to get back to Index</h3>
{% endblock %}

test_pro_temp/templates/test_app_temp/register.html
{% extends "base.html" %}
  {% block body_block %}
  <h1>Registration form: </h1>
  <h3>Please fill in the below details</h3>
  <div class="jumbotron">
    <form enctype="multipart/form-data" method="POST">
      {{ user_form.as_p }}
      {{ userinfo_form.as_p }}
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" value="Register">
    </form>
    <h3> Please <a href="{% url 'index' %}">  click here</a> to get back to Index</h3>
  </div>
  {% endblock %}

test_pro_temp/templates/test_app_temp/ulogin.html
{% extends 'base.html' %}
{% block body_block %}

<h1>LOGIN</h1>
<h2>Please proceed to the registration page if you haven't registered yet</h2>
<div class="jumbotron">
  <form class="" action="{% url 'tapp:user_login' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
    <label for="username">Username: </label>
    <input type="text" name="username">
    </div>
    <div class="form-group">
    <label for="password">Password: </label>
    <input type="password" name="password">
    </div>

    <input type="submit" name="" value="Login">

  </form>
</div>

{% endblock %}